name: cotizador_agente
description: Soy Socio GNP.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  localstorage: ^2.0.0
  table_calendar: ^2.0.2
  flutter_linkify: ^2.1.0
  url_launcher: ^5.1.4
  flutter_webview_plugin: 0.3.11
  jiffy: ^2.2.0
  flutter_tags: 0.4.5
  open_file: ^2.0.3
  dio: ^3.0.2
  flutter_pdfview: ^1.0.0+10
  flutter_plugin_pdf_viewer: ^1.0.7
  cached_network_image: ^2.0.0
  connectivity: 0.4.0+1
  local_auth: ^0.6.0+1
  device_info: ^0.4.0+2
  xml2json: ^4.0.0
  flutter_slidable: ^0.5.3
  date_format: ^1.0.6
  image_picker: ^0.6.1+4
  flutter_local_notifications: ^1.1.3
  loading_overlay: ^0.2.1
  modal_bottom_sheet: ^0.2.0
  package_info: ^0.4.1
  version: ^1.2.0
  shimmer: ^1.1.1
  firebase_remote_config: ^0.4.1
  firebase_crashlytics: ^0.2.4
  firebase_analytics: ^6.2.0
  firebase_core: ^0.5.2
  firebase_performance: ^0.3.2
  cloud_firestore: ^0.14.1+3

  # share_extend: ^1.0.9 custom #
  share_extend:
    path: ./lib/ExternalCustomPackages/custom_share_extend

  #Busqueda en textfields
  flutter_typeahead: ^1.8.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 3.0.0

flutter:

  uses-material-design: true
  assets:

    - assets/
    - assets/icon/
    - assets/icon/cotizador/
    - assets/icon/login/
    - assets/icon/splash/
    - assets/img/
    - images/
    - images/perfil/
    - images/perfil/contacto/
    - images/perfil/familiares/
    - images/perfil/otros/
    - images/perfil/perfil/
    - images/perfil/salud/


  fonts:
    - family: OpenSansRegular
      fonts:
          - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf


flutter_icons:
  image_path: "images/ic_launcher.png"
  android: true
  ios: true