name: cotizador_agente
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.3
  connectivity: ^2.0.1
  device_info: ^1.0.0
  local_auth: 0.6.3+4
  page_transition: ^1.1.6
  encrypt: ^4.1.0
  rflutter_alert: ^1.1.0
  flutter_switch: ^0.2.0
  simple_image_crop: 0.1.3
  image_picker: 0.6.7+22
  shared_preferences: ^0.5.3+4
  firebase_remote_config: ^0.6.0
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_performance: ^0.5.0+1
  cached_network_image: ^2.0.0
  shimmer: ^1.1.2
  modal_bottom_sheet: ^0.2.0
  loading_overlay: ^0.2.1
  dio: ^3.0.10
  flutter_pdfview: ^1.0.4
  flutter_plugin_pdf_viewer: ^1.0.7
  flutter_tags: 0.4.5
  open_file: ^3.0.3
  jiffy: ^2.2.0
  url_launcher: ^5.7.10
  firebase_database: ^6.0.0
  webview_flutter: ^1.0.7
  flutter_webview_plugin: 0.3.11
  introduction_screen: 1.0.7
  flutter_inappwebview: ^4.0.0
  custom_switch: ^0.0.1
  multi_image_picker: ^4.7.15
  flutter_keyboard_aware_dialog: ^1.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/login/
    - assets/home/
    - assets/images/
    - assets/home/boarding/
    - assets/icon/
    - assets/icon/cotizador/
    - assets/icon/login/
    - assets/icon/splash/
    - images/
    - images/perfil/
    - images/perfil/contacto/
    - images/perfil/familiares/
    - images/perfil/otros/
    - images/perfil/perfil/
    - images/perfil/salud/


  fonts:
    - family: FlamanteRoma
      fonts:
        - asset: assets/fonts/Flamante-Roma-Medium.ttf
        - asset: assets/fonts/Lato-Bold.ttf

    - family: Contratacion_icons
      fonts:
        - asset: assets/fonts/ContratacionIcons.ttf